name: Main

on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    container: openjdk
    
    steps:
      - uses: actions/checkout@v3
      - name: Compile Java Code
        run: javac -cp "Projects/P1/tests/junit-4.10.jar:src/:tests/" Projects/P1/src/*.java Projects/P1/tests/*.java
        
      - name: Compile Java Code and Run TestPacManValidMoves
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
          working-directory: Projects/P1
          
      - name: Compile Java Code and Run TesGhostValidMoves
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
          working-directory: Projects/P1
          
      - name: Compile Java Code and Run TestMapMove
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
          working-directory: Projects/P1
