name: Main

on:
  push:

jobs:

  compile:
    runs-on: ubuntu-latest
    container: openjdk
    
    steps:
      - uses: actions/checkout@v3
      - name: Compile Java Code

        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        working-directory: Projects/P1
        
      - name: Compile Java Code and Run TestPacManValidMoves
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
        working-directory: Projects/P1
          
      - name: Compile Java Code and Run TestGhostValidMoves
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
        working-directory: Projects/P1
          
      - name: Compile Java Code and Run TestMapMove
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
        working-directory: Projects/P1

 
      - name: Compile Java Code and Run TestGhostMove
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestPacManMove
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestMapGetLoc
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
        working-directory: Projects/P1
        
      - name: Compile Java Code and Run TestMapAttack
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestGhostInRange
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostInRange
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestPacManInRange
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManInRange
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestConsume
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestAttack
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestMapEatCookie
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
        working-directory: Projects/P1
