name: Main

on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    container: openjdk
    
    steps:
      - uses: actions/checkout@v3
      - name: Compile Java Code

        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestConsume
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestAttack
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
        working-directory: Projects/P1

      - name: Compile Java Code and Run TestMapEatCookie
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
        working-directory: Projects/P1
